<a href="https://colab.research.google.com/github/jenrios14/Data-Science-FEM-Study-Group/blob/master/Copia_de_2_1_Lineal_Algebra_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1.

* Print the sum of matrixes A and B

$$ A =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
5 & 6
\end{array}\right) + B =
\left(\begin{array}{cc} 
6 & 5\\
4 & 3\\
2 & 1 
\end{array}\right)
$$ 

In [4]:
# Answer 1.
import numpy as np 
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
matriz = A+B
print(matriz)
#print(A)




[[7 7]
 [7 7]
 [7 7]]


# Question 2

* Print the sum of matrix + scalar.

$$ M =
\left(\begin{array}{cc} 
6 & 3\\
9 & 5\\
4 & 8
\end{array}\right) + N =
\left(\begin{array}{cc} 
2.5 \\ 
\end{array}\right)
$$ 

In [12]:
# Answer 2.
import numpy as np 
M = np.array([[6,3],[9,5],[4,8]])
N = [2.5] - M
print(N)

[[-3.5 -0.5]
 [-6.5 -2.5]
 [-1.5 -5.5]]


# Question 3.

* Print the transposed matrix of  $J$  -->  $J^t$. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [6]:
# Answer 3.
import numpy as np 
J = np.array([[9,2,3],[3,7,4],[5,6,9]])
JT = J.transpose()
print(JT)

[[9 3 5]
 [2 7 6]
 [3 4 9]]


# Question 4.

* For the $ J ^ t $ matrix, calculate your transpose to obtain the original matrix J. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [2]:
# Answer 4.
import numpy as np 
JT = np.array([[9,3,5],[2,7,6],[3,4,9]])
J = JT.transpose()
print(J)




[[9 2 3]
 [3 7 4]
 [5 6 9]]


# Question 5.

* 
What are the missing values? 

$$
\left(\begin{array}{cc} 
? & 2\\
0 & 2
\end{array}\right)
\left(\begin{array}{cc} 
1 & 0 \\ 
1 & ? 
\end{array}\right)
$$ 

 * so that the answer is like this:
$
\left(
 \begin {array}{ll} 
1 & 0 \\
0   & 0
\end{array}
\right)
$

- [ A ] = 1 y 1
- [ B ] = 0 y 1
- [ C ] = 1 y 0
- [ D ] = 0 y 0

*  Print the result and the answer.

In [11]:
# Answer 5.
import numpy as np
A = np.array([[0,2],[0,2]])
B = np.array([[1,0],[1,0]])
C = np.dot(A,B)
print(C)

[[2 0]
 [2 0]]


# Question 6.
* ¿ What is the dot product matrixes  $L$ y $K$ = : ?

$$ L =
\left(\begin{array}{cc} 
3 & 5 \\
7 & 1 \\
\end{array}\right) K =
\left(\begin{array}{cc} 
3 & 12  \\
6 & 4  \\
\end{array}\right)
$$ 

In [10]:
# Answer 6.
import numpy as np 
L = np.array([[3,5],[7,1]])
K = np.array([[3,12],[6,4]])
DP = np.dot(L,K)
print(DP)

[[39 56]
 [27 88]]


# Question 7.

* ¿ What is the determinant of the following matrix  ? (Print the answer)

$
\left(
\begin {array}{ll} 
1 & 2 & 0 \\
1 & 2 & 0 \\
0 & 1 & 1 \\
\end{array}
\right)
$

- [ A ] = 1 
- [ B ] = 0 
- [ C ] = 5
- [ D ] = -5



In [17]:
# Answer 7.
import numpy as np
M = np.array([[1,2,0],[1,2,0],[0,1,1]])
DM = np.linalg.det(M)
print(DM)

0.0


# Question 8.

* ¿ What is the determinant of the following matrix ? (Print the answer)

$
\left(
\begin {array}{ll} 
0 & 1 & 1 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{array}
\right)
$

- [ A ] = 0 
- [ B ] = -1 
- [ C ] = 3
- [ D ] = 1


In [16]:
# Answer 8.
import numpy as np
M = np.array([[0,1,1],[1,0,0],[0,0,1]])
DM = np.linalg.det(M)
print(DM)

-1.0


# Question 9

* ¿What is the missing value?
$$ 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right) 
\left(\begin{array}{cc} 
0 \\ 
? \\
16 \\
\end{array}\right) =
\left(\begin{array}{cc} 
4 \\ 
10 \\
16 \\
\end{array}\right)
$$ 

In [25]:
import numpy as np
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
B= np.array([[0],[-22],[16]])
C = np.dot(A,B)
print(C)

[[  4]
 [-14]
 [-32]]
